/// <reference types="@types/serviceworker" />

// Custom Service Worker for HustlePay PWA with Push Notifications
// Generated by vite-plugin-pwa with injectManifest strategy

// @ts-ignore
const manifest = self.__WB_MANIFEST || [];

const CACHE_NAME = 'hustlepay-v1';
const STATIC_ASSETS = [
  '/',
  '/index.html',
  '/favicon.png',
  '/apple-touch-icon.png',
  '/pwa-192x192.png',
  '/pwa-512x512.png',
  '/manifest.webmanifest'
];

// VAPID Public Key - Must match the one used in the app
const VAPID_PUBLIC_KEY = 'BEl62iUYgUivxIkv69yViEuiBIa-Ib9-SkvMeAtA3LFgDzkrxZJjSgSnfckjBJuBkr3qBUYIHBQFLXYp5Nksh8U';

// Convert base64 string to Uint8Array
function urlBase64ToUint8Array(base64String: string): Uint8Array {
  const padding = '='.repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/');
  const rawData = atob(base64);
  const outputArray = new Uint8Array(rawData.length);
  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray;
}

// Install event - cache static assets
self.addEventListener('install', (event: ExtendableEvent) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      return cache.addAll(STATIC_ASSETS);
    }).then(() => {
      self.skipWaiting();
    })
  );
});

// Activate event - clean up old caches
self.addEventListener('activate', (event: ExtendableEvent) => {
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames
          .filter((name) => name !== CACHE_NAME)
          .map((name) => caches.delete(name))
      );
    }).then(() => {
      self.clients.claim();
    })
  );
});

// Fetch event - serve from cache, fallback to network
self.addEventListener('fetch', (event: FetchEvent) => {
  // Skip non-GET requests
  if (event.request.method !== 'GET') return;

  // Skip video files - handled by runtime caching
  if (event.request.url.includes('.mp4') || event.request.url.includes('.webm')) return;

  event.respondWith(
    caches.match(event.request).then((cachedResponse) => {
      if (cachedResponse) {
        return cachedResponse;
      }

      return fetch(event.request).then((networkResponse) => {
        // Don't cache non-successful responses
        if (!networkResponse || networkResponse.status !== 200 || networkResponse.type !== 'basic') {
          return networkResponse;
        }

        // Clone the response
        const responseToCache = networkResponse.clone();
        caches.open(CACHE_NAME).then((cache) => {
          cache.put(event.request, responseToCache);
        });

        return networkResponse;
      }).catch(() => {
        // Offline fallback for HTML pages
        if (event.request.mode === 'navigate') {
          return caches.match('/index.html');
        }
      });
    })
  );
});

// Push event - handle incoming push notifications
self.addEventListener('push', (event: PushEvent) => {
  console.log('[SW] Push received:', event);

  let notificationData: NotificationPayload = {
    title: 'HustlePay',
    body: 'You have a new notification',
    icon: '/pwa-192x192.png',
    badge: '/pwa-192x192.png',
    tag: 'default',
    data: {},
    actions: [
      { action: 'view', title: 'View' },
      { action: 'dismiss', title: 'Dismiss' }
    ],
    requireInteraction: false,
    vibrate: [100, 50, 100]
  };

  if (event.data) {
    try {
      const payload = event.data.json();
      notificationData = { ...notificationData, ...payload };
    } catch (e) {
      console.error('[SW] Failed to parse push data:', e);
      notificationData.body = event.data.text() || notificationData.body;
    }
  }

  // Check if we should show notification (focus check)
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      const isAppFocused = clientList.some((client) => client.focused && client.url.includes(self.location.origin));

      // Don't show notification if app is focused and it's not high priority
      if (isAppFocused && !notificationData.requireInteraction) {
        // Still send to app for in-app notification
        clientList.forEach((client) => {
          client.postMessage({
            type: 'PUSH_NOTIFICATION',
            payload: notificationData
          });
        });
        return;
      }

      // Show notification
      return self.registration.showNotification(notificationData.title, {
        body: notificationData.body,
        icon: notificationData.icon,
        badge: notificationData.badge,
        tag: notificationData.tag,
        data: notificationData.data,
        actions: notificationData.actions,
        requireInteraction: notificationData.requireInteraction,
        vibrate: notificationData.vibrate,
        timestamp: Date.now()
      });
    })
  );
});

// Notification click event
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  console.log('[SW] Notification clicked:', event);

  event.notification.close();

  const action = event.action;
  const data = event.notification.data || {};

  // Handle action buttons
  if (action === 'dismiss') {
    return;
  }

  // Determine URL to open based on notification data
  let url = '/';

  if (data.bookingId) {
    url = `/booking-flow/${data.bookingId}`;
  } else if (data.chatId) {
    url = `/chat/${data.chatId}`;
  } else if (data.disputeId) {
    url = `/disputes`;
  } else if (data.type === 'artisan_approved') {
    url = '/';
  }

  // Focus existing window or open new one
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      // Check if there's already a window open
      for (const client of clientList) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          // Navigate to the correct page
          client.postMessage({
            type: 'NAVIGATE',
            url
          });
          return client.focus();
        }
      }

      // Open new window
      return clients.openWindow(url);
    })
  );
});

// Notification close event
self.addEventListener('notificationclose', (event: NotificationEvent) => {
  console.log('[SW] Notification closed:', event.notification.tag);
  // Track notification dismissal if needed
});

// Background sync for offline actions
self.addEventListener('sync', (event: SyncEvent) => {
  console.log('[SW] Background sync:', event.tag);

  if (event.tag === 'send-message') {
    event.waitUntil(sendPendingMessages());
  } else if (event.tag === 'update-booking') {
    event.waitUntil(syncBookingUpdates());
  }
});

// Periodic background sync (if supported)
self.addEventListener('periodicsync', (event: PeriodicSyncEvent) => {
  console.log('[SW] Periodic sync:', event.tag);

  if (event.tag === 'check-notifications') {
    event.waitUntil(checkForNotifications());
  }
});

// Message event - communicate with app
self.addEventListener('message', (event: ExtendableMessageEvent) => {
  console.log('[SW] Message received:', event.data);

  if (event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  } else if (event.data.type === 'GET_SUBSCRIPTION') {
    // Return current push subscription
    self.registration.pushManager.getSubscription().then((subscription) => {
      event.ports[0].postMessage({ subscription });
    });
  } else if (event.data.type === 'SUBSCRIBE_PUSH') {
    // Subscribe to push
    subscribeToPush(event.data.userId).then((subscription) => {
      event.ports[0].postMessage({ subscription });
    });
  } else if (event.data.type === 'UNSUBSCRIBE_PUSH') {
    // Unsubscribe from push
    unsubscribeFromPush().then((success) => {
      event.ports[0].postMessage({ success });
    });
  } else if (event.data.type === 'SHOW_LOCAL_NOTIFICATION') {
    // Show local notification from app
    self.registration.showNotification(event.data.payload.title, event.data.payload);
  }
});

// Helper: Subscribe to push notifications
async function subscribeToPush(userId: string): Promise<PushSubscription | null> {
  try {
    const subscription = await self.registration.pushManager.subscribe({
      userVisibleOnly: true,
      applicationServerKey: urlBase64ToUint8Array(VAPID_PUBLIC_KEY)
    });

    // Send subscription to server (or store locally)
    await sendSubscriptionToServer(subscription, userId);

    return subscription;
  } catch (error) {
    console.error('[SW] Failed to subscribe to push:', error);
    return null;
  }
}

// Helper: Unsubscribe from push notifications
async function unsubscribeFromPush(): Promise<boolean> {
  try {
    const subscription = await self.registration.pushManager.getSubscription();
    if (subscription) {
      await subscription.unsubscribe();
      await removeSubscriptionFromServer(subscription);
      return true;
    }
    return false;
  } catch (error) {
    console.error('[SW] Failed to unsubscribe from push:', error);
    return false;
  }
}

// Helper: Send subscription to server
function sendSubscriptionToServer(subscription: PushSubscription, userId: string): Promise<void> {
  return new Promise(async (resolve, reject) => {
    try {
      const db = await openDB();
      const tx = db.transaction('subscriptions', 'readwrite');
      const store = tx.objectStore('subscriptions');
      const request = store.put({ userId, subscription, timestamp: Date.now() });
      
      tx.oncomplete = () => resolve();
      tx.onerror = () => reject(tx.error);
      request.onerror = () => reject(request.error);
    } catch (e) {
      reject(e);
    }
  });
}

// Helper: Remove subscription from server
function removeSubscriptionFromServer(subscription: PushSubscription): Promise<void> {
  return new Promise(async (resolve, reject) => {
    try {
      const db = await openDB();
      const tx = db.transaction('subscriptions', 'readwrite');
      const store = tx.objectStore('subscriptions');
      const request = store.openCursor();
      
      request.onsuccess = (event) => {
        const cursor = (event.target as IDBRequest<IDBCursorWithValue | null>).result;
        if (cursor) {
          if (cursor.value.subscription.endpoint === subscription.endpoint) {
            cursor.delete();
          }
          cursor.continue();
        }
      };
      
      tx.oncomplete = () => resolve();
      tx.onerror = () => reject(tx.error);
      request.onerror = () => reject(request.error);
    } catch (e) {
      reject(e);
    }
  });
}

// Helper: Open IndexedDB
function openDB(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const request = indexedDB.open('HustlePaySW', 1);
    request.onerror = () => reject(request.error);
    request.onsuccess = () => resolve(request.result);
    request.onupgradeneeded = (event) => {
      const db = (event.target as IDBOpenDBRequest).result;
      if (!db.objectStoreNames.contains('subscriptions')) {
        db.createObjectStore('subscriptions', { keyPath: 'id', autoIncrement: true });
      }
      if (!db.objectStoreNames.contains('pendingMessages')) {
        db.createObjectStore('pendingMessages', { keyPath: 'id', autoIncrement: true });
      }
      if (!db.objectStoreNames.contains('bookingUpdates')) {
        db.createObjectStore('bookingUpdates', { keyPath: 'id', autoIncrement: true });
      }
    };
  });
}

// Helper: Send pending messages when online
async function sendPendingMessages(): Promise<void> {
  // Implementation for offline message queue
  console.log('[SW] Sending pending messages...');
}

// Helper: Sync booking updates
async function syncBookingUpdates(): Promise<void> {
  // Implementation for offline booking updates
  console.log('[SW] Syncing booking updates...');
}

// Helper: Check for notifications (periodic sync)
async function checkForNotifications(): Promise<void> {
  // In a real app, this would fetch from your server
  console.log('[SW] Checking for notifications...');
}

// Type definitions
interface NotificationPayload {
  title: string;
  body: string;
  icon?: string;
  badge?: string;
  tag?: string;
  data?: Record<string, unknown>;
  actions?: Array<{ action: string; title: string; icon?: string }>;
  requireInteraction?: boolean;
  vibrate?: number[];
  timestamp?: number;
}

interface PushSubscriptionData {
  endpoint: string;
  keys: {
    p256dh: string;
    auth: string;
  };
}

export {};